# Press esc to exit the widget and e to enter the selected widget.
# Press s to sort the processes by the selected column.
# Press q to quit the application.
# Press ? to show this help message.

[flags]

# Whether to hide the average cpu entry.
hide_avg_cpu = true

# Whether to use dot markers rather than braille.
dot_marker = true

# The update rate of the application.
rate = "1s"

# Whether to put the CPU legend to the left.
cpu_left_legend = true

# The temperature unit. One of the following, defaults to "c" for Celsius:
temperature_type = "celsius"

# Expand selected widget upon starting the app
expanded = true

hide_table_gap = true

# Show tree mode by default in the processes widget.
tree = true

# Shows GPU(s) information
enable_gpu = true

# Shows cache and buffer memory
enable_cache_memory = true

# These are all the components that support custom theming.  Note that colour support
# will depend on terminal support.
#[styles] # Uncomment if you want to use custom styling

# Built-in themes. Valid values are:
# - "default"
# - "default-light"
# - "gruvbox"
# - "gruvbox-light"
# - "nord"
# - "nord-light".
#
# This will have the lowest precedence if a custom colour palette is set,
# or overridden if the command-line flag for a built-in theme is set.
theme = "gruvbox"

[styles.cpu]
all_entry_color = "dark gray"
avg_entry_color = "dark gray"
cpu_core_colors = ["gray", "gray", "gray", "gray", "gray", "gray", "gray", "gray"]

[styles.memory]
ram_color = "gray"
cache_color = "gray"
swap_color = "gray"
arc_color = "gray"
gpu_colors = ["gray", "gray", "gray", "gray", "gray", "gray"]

[styles.tables]
headers = {color = "red", bold = true}

[styles.graphs]
graph_color = "red"
legend_text = {color = "red"}

[styles.widgets]
border_color = "red"
selected_border_color = "light red"
widget_title = {color = "red"}
text = {color = "gray"}
selected_text = {color = "black", bg_color = "light red"}
disabled_text = {color = "dark gray"}

# Layout - layouts follow a pattern like this:
# [[row]] represents a row in the application.
# [[row.child]] represents either a widget or a column.
# [[row.child.child]] represents a widget.
#
# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
# All layout components have a ratio value - if this is not set, then it defaults to 1.
# The default widget layout:
[[row]]
  ratio=30
  [[row.child]]
    type="cpu"
    default = true
    graph = true
[[row]]
    ratio=30
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="temp"
      [[row.child.child]]
        type="disk"
    [[row.child]]
      ratio=4
      type="mem"
[[row]]
  ratio=60
  [[row.child]]
    type="proc"
    default=true